### ISSUE TITLE
UI Component | Set background image

### ISSUE THREAD

**Issue by vieraboschkova** [Rednaxela700/CC-Project-2#9]
old hash: #6
Acceptance Criteria:
Verify or consult before submitting the task!

- [x]  Export a background image from a Figma project.
- [x]  Set an image as an application background.
- [x]  The background must always cover the entire screen, no matter what is the application size.

**Comment by Rednaxela700** [comment]
As long as this task is being blocked I’d consider a post explaining why you cannot proceed while it’s marked “in progress”.
 
A special label might help to move on with ease 👷‍♂️
